spring:
  application:
    name: WelcomeRestfulApplication
  boot:
    admin:
      client:
        url: http://localhost:1111/
server:
  port: 9092
management:
  endpoints:
    web:
      exposure:
        include: '*'
