spring:
  application:
    name: GreetRestfulApplication
  boot:
    admin:
      client:
        url: http://localhost:1111/
  zipkin:
    baseUrl: http://localhost:9411/
management:
  endpoints:
    web:
      exposure:
        include: '*'
