spring:
  application:
    name: GreetRestfulApplication
  boot:
    admin:
      client:
        url: http://localhost:1111/
  zipkin:
    baseUrl: http://localhost:9411/
server:
  port: 9091
management:
  endpoints:
    web:
      exposure:
        include: '*'
